services:
  # Evento Web Service
  - type: web
    name: evento
    runtime: node
    plan: starter
    repo: https://github.com/nusaifpk/evento.git
    rootDir: .
    buildCommand: npm run render-build-only
    startCommand: npm run render-start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: STANDALONE_SERVER
        value: true
      - key: AWS_REGION
        value: us-east-1
